name: Format

on:
  schedule:
      # every 2 hours
    - cron: "0 */2 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3

      # Other steps that change files in the repository

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
